layout: page
title: CTS 285 Project 1 - Llama Man
description: llama llama llama llama llama llama llama llama llama
permalink: /mrchiff.github.io
# theme: jekyll-theme-cayman
# theme: jekyll-theme-moonwalk
# theme: jekyll-theme-time-machine
theme: jekyll-theme-architect
# theme: jekyll-theme-merlot